version: '3.8'

services:
  backend:
    build:
      context: ./mindvault-backend
      dockerfile: Dockerfile
    container_name: backend
    working_dir: /usr/src/app
    ports:
      - "4001:4000"
    environment:  
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - PORT=4000
    env_file:
      - ./mindvault-backend/.env
    depends_on:
      - mongo
    networks:
      - mynetwork

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - mynetwork

  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mynetwork

volumes:
  mongo_data:

networks:
  mynetwork:
