name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push backend Docker image
        run: |
          docker build -t mohammadshahidbeigh/mindvault-backend:latest -f ./backend/Dockerfile 
          docker save backend-app | ssh -i "your-key.pem" ubuntu@your-ec2-public-ip "docker load && docker run -d -p 4000:4000 backend-app"

      - name: Build and push frontend Docker image
        run: |
          docker build -t mohammadshahidbeigh/mindvault-frontend:latest -f ./frontend/Dockerfile .
          docker save frontend-app | ssh -i "your-key.pem" ubuntu@your-ec2-public-ip "docker load && docker run -d -p 3000:3000 frontend-app"



