name: Deploy MindVault

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push backend image
      run: |
        docker build -t mohammadshahidbeigh/mindvault-backend:latest ./mindvault-backend
        docker push mohammadshahidbeigh/mindvault-backend:latest

    - name: Build and push frontend image
      run: |
        docker build -t mohammadshahidbeigh/mindvault-frontend:latest .
        docker push mohammadshahidbeigh/mindvault-frontend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          docker pull mohammadshahidbeigh/mindvault-backend:latest
          docker pull mohammadshahidbeigh/mindvault-frontend:latest
          docker stop $(docker ps -q)
          docker run -d -p 4000:4000 mohammadshahidbeigh/mindvault-backend:latest
          docker run -d -p 3000:80 mohammadshahidbeigh/mindvault-frontend:latest





