name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build and push frontend Docker image
        run: |
          docker buildx build -t mohammadshahidbeigh/mindvault-frontend:latest -f ./Dockerfile .  # Added the build context "."
          docker push mohammadshahidbeigh/mindvault-frontend:latest

      - name: Build and push backend Docker image
        run: |
          docker buildx build -t mohammadshahidbeigh/mindvault-backend:latest -f ./mindvault-backend/Dockerfile .  # Added the build context "."
          docker push mohammadshahidbeigh/mindvault-backend:latest

      - name: SSH and deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull mohammadshahidbeigh/mindvault-frontend:latest
            docker pull mohammadshahidbeigh/mindvault-backend:latest
            docker-compose down
            docker-compose up -d


