name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: mohammadshahidbeigh/mindvault-frontend:latest

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./mindvault-backend
          file: ./mindvault-backend/Dockerfile
          push: true
          tags: mohammadshahidbeigh/mindvault-backend:latest

      - name: SSH and deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/mindVault   # Navigate to the directory where docker-compose.yml is located
            docker pull mohammadshahidbeigh/mindvault-frontend:latest
            docker pull mohammadshahidbeigh/mindvault-backend:latest
            docker-compose down
            docker-compose up -d



